name: sidewalk-quality-analysis
channels:
  - conda-forge
dependencies:
  - python=3.9
  - notebook=6.4.*
  - numpy=1.21.*
  - matplotlib=3.5.*
  - seaborn=0.11.*
  - pandas=1.3.*
  - jupyter_contrib_nbextensions
  - scikit-learn=1.0.1